spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true
    url: jdbc:h2:mem:maindb
    user: sa
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    #    properties:
#      hibernate:
#        format_sql: true
    show-sql: true